### ISSUE TITLE
I'm having issues with MongoDB and other problems in this project. I need to run this project only on localhost. Could you please help me understand how to use this repository and run it directly on my machine? It's urgent because of college commitments. I appreciate any assistance you can provide. U can give me total guide to run this project. @bhuvanbhoge my instagram/linkedin id. I hope you understand me, help me asap😊

### ISSUE THREAD

**Issue by dsbhuvanneubrain** [sohomofficial/imaginify#9]
error 
1)mongodb collection is not visible
2)because of this i cant go furthur

./lib/actions/image.actions.ts
./app/(root)/page.tsx
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (101kiB) impacts deserialization performance (consider using Buffer 
instead and decode when needed)
Terminate batch job (Y/N)?

**Comment by sohomofficial** [comment]
Hey friend!

I guess you are having issues in setting up your environment variables properly and managing the external softwares that are implemented here. Don't worry, you can refer to the video of JavaScript Mastery (attached below),  which provides a complete video tutorial of this project. Skip to the parts where MongoDB cluster is being set up or other related set ups, which you are having trouble with. I hope that, you getting a visual solution to your problems will be better than me typing it here.

Hope it helps 🙂

Tutorial : [link](https://youtu.be/Ahwoks_dawU?si=a5tkAsxJzq0aEs0w)

**Comment by dsbhuvanneubrain** [comment]
Thank you, Soham, for helping me. I've already seen that video and I
explored whether anyone has created that project so I can ask how to create
it, and I found you. I followed all the steps exactly as the tutorial says,
but from the MongoDB section, my project is collapsing. That's why I needed
someone who can fix bugs or guide me through this. Have you done exactly
the same steps as he did? Did you also encounter any problems while dealing
with the .env.local files' content? Thank you again. Can you help me in
this situation?

**Comment by sohomofficial** [comment]
Ahh I got your situation, and honestly I had no problem while dealing with the .env.local files' content as everything in this repository was made by me from scratch, taking guidance from the tutorial. 

But unfortunately I can't help you any further at the moment for being out of station 😔. But got some suggestions for you:-

- You can public your own imaginfu repository on GitHub and create an issue there, where people will get to see the actual fault in your code and help you fix it
- You can also ask for help in the help forum channel in.official JavaScript Mastery discord server, where you can get support related to it. 

Hope these suggestions come in some use to you and help you solve your problems. All the best 👍
